{
 "title": "IoT-SmartHome",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DMS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r.name == \"DMS\")"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"Distance\")"
    }
   ]
  },
  {
   "title": "Door-sensor",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"Door-sensor\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"Humidity\")"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"Motion\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot-smart-home\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"Temperature\")"
    }
   ]
  }
 ]
}